run-name: Deploy the API
name: Deploy

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
      - 14-pipeline

jobs:
  build:
    name: "Build docker"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: start container
        run: docker-compose -f ./config/docker/docker-compose.test.yml up --build -d

      - name: wait 10 sec
        run: sleep 10

      - name: stop container
        run: docker-compose -f ./config/docker/docker-compose.test.yml down

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: run unit test
        run: echo "Deploy api"