run-name: Deploy the API
name: Deploy

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: "Build docker"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: start container
        run: make

      - name: wait 10 sec
        run: sleep 10

      - name: stop container
        run: make stop

  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: run unit test
        run: echo "Deploy api"