run-name: Run API integration test
name: Integration test

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
      - 14-pipeline

jobs:
  integrationTest:
    name: "Integration test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run unit tests
        run: go test ./tests/integrationTests/...