run-name: Run API integration test
name: Integration test

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: "build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

  integrationTest:
    name: "Integration test"
    runs-on: ubuntu-latest
    needs: ["Unit test"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: run unit test
        run: echo "this is the integration test"