run-name: Run API unit test
name: Unit test

on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
      - develop
      - 14-pipeline

jobs:
  unitTest:
    name: "Unit test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run unit tests
        run:  go test ./tests/unitTests/...